#pragma once

#define VIAL_KEYBOARD_UID {0x8B, 0x95, 0x1F, 0xA3, 0x58, 0x07, 0xAE, 0xA2}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 12 }

#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 1
#define RSPC_KEYS KC_RSFT, KC_LSFT, KC_NUBS

#define USB_POLLING_INTERVAL_MS 1
#define QMK_KEYS_PER_SCAN 12
