#define LSPO_KEYS KC_LSFT, KC_TRNS, KC_NUBS
#define RSPC_KEYS KC_RSFT, KC_LSFT, KC_NUBS
#define LCPO_KEYS KC_LCTL, KC_RALT, KC_QUOT
#define RCPC_KEYS KC_RCTL, KC_RALT, KC_BSLS
#define LAPO_KEYS KC_LALT, KC_RALT, KC_LBRC
#define RAPC_KEYS KC_RALT, KC_RALT, KC_RBRC
